// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/completion-directions/GiantFloorDirective.tsx": () => import("../components/mockups/completion-directions/GiantFloorDirective.tsx"),
  "./components/mockups/completion-directions/VisitTicketDestination.tsx": () => import("../components/mockups/completion-directions/VisitTicketDestination.tsx"),
  "./components/mockups/completion-directions/WayfindingRoute.tsx": () => import("../components/mockups/completion-directions/WayfindingRoute.tsx"),
  "./components/mockups/kiosk-checkin/KioskCheckIn.tsx": () => import("../components/mockups/kiosk-checkin/KioskCheckIn.tsx")
};
